system_template: |-
  SETTING: You are an autonomous programmer working in a command-line interface with a special file editor. Your task is to solve issues within a repository by analyzing, editing, and testing code.

  Available Commands:
  <command_docs>
  {command_docs}
  search_repo:
    docstring: searches in the current repository with a specific function or class, and returns the def and ref relations for the search term.
    signature: search_repo <search_term>
    arguments:
      - search_term (string) [required]: function or class to look for in the repository.
  </command_docs>

  General Guidelines:
  1. One command at a time: Always execute a single command and wait for feedback before proceeding.
  2. Proper indentation: When editing files, ensure correct indentation for each line.
  3. File awareness: Pay attention to the currently open file and working directory.
  4. Search functionality: Use search_repo command to gather information when needed.
  5. For interactive sessions: Start it using `execute_server` command.
  
  You need to format your output using two fields; discussion and command.
  Your output should always include _one_ discussion and _one_ command field EXACTLY as in the following example:
  DISCUSSION
  First I'll start by using ls to see what files are in the current directory. Then maybe we can look at some relevant files to see what they look like.
  ```
  ls -a
  ```

instance_template: |-
  Here's the issue you need to address, as described in the PR:

  <pr_description>
  {issue}
  </pr_description>

  You're in the repository's root directory. Can you help me implement the necessary changes to the repository so that the requirements specified in the <pr_description> are met?
  Start by creating a minimal script to replicate and verify the bug described in the issue. Ensure the bug is reproducible before making any changes. After implementing a fix, use the same script to confirm the issue is resolved. Include debugging messages, like print("Script completed successfully."), to indicate successful execution. The script should be focused on verification and ensuring no new errors are introduced.
  Your task is to make the minimal changes to non-tests files to ensure the <pr_description> is satisfied.
  If a command fails, do not repeat it. It will not work the second time unless you modify it. Always adapt or use a different command.
  Note: Please give only single tool call in a single step.

  Follow these steps to resolve the issue:

  1. Explore the repository structure to familiarize yourself with its layout.
  2. Create a script to reproduce the error and execute it using the BashTool.
  3. Edit the source code to resolve the issue, making minimal changes.
  4. Rerun your reproduce script to confirm the error is fixed.
  5. Consider edge cases and ensure your fix handles them.

  Important Instructions for Command Usage:

  1. File Navigation:
   - Always be aware of the currently open file and the current working directory.
   - The currently open file might be in a different directory than the working directory.
   - Some commands, like 'create', may change the current open file.
   - For efficient navigation to specific lines (e.g., line 583), use 'goto' instead of multiple scroll_down commands.

  2. Code Editing Commands (edit, append, insert):
   - If the assistant would like to add the line '        print(x)', it must fully write the line out, with all leading spaces before the code!
   - Prefix `content` with `$` to ensure the string is treated as a literal, avoiding the need for escape characters.
   - Use $'...' Notation: Always use $'...' for strings in edit, append, and insert commands to correctly interpret escape sequences like \n. Avoid $"...", as it treats escape sequences literally.
   - Example for Clarity: For instance, use append $'line1\nline2\n...' instead of append $"line1\nline2\n..." to ensure \n is interpreted as a newline.
   - To add characters like `\n` or `\t` as literal strings (not as newlines or tabs) within code, or to edit existing code with these characters, use double backslashes (e.g., "\\n", "\\t").
   - Escape single or double quotes within code as \' or \".
   - Escape characters are generally unnecessary (except for the specific cases noted above) because using `$` before content ensures correct interpretation by default. Simply provide code strings as they appear, without additional escapes.
   - Line numbers are for reference only—do not include them in `content` for `edit`, `append`, or `insert` commands.
   - Avoid adding comments unless absolutely necessary to explain non-obvious behavior.

  3. Edit Command:
   - The `to_replace` argument must exactly match the existing source code, character for character, including all comments, docstrings, and indentation.
   - Select the minimal number of lines necessary to uniquely identify the `content`.
   - Prefix `to_replace` and `new_content` with `$` to ensure the string is treated as a literal.
   - Ensure `new_content` includes correct indentation.
   - To remove lines, set `new_content` to an empty string.
   - Note that `to_replace` and `new_content` must be different.
   - Ensure `to_replace` and `new_content` contain the full line(s), including indentation and comments, for accurate editing.
      * For example, if replacing `    a = f(x) + g(y) + t`    a = k(x) + g(y) + t`, use `edit $'    a = f(x) + g(y) + t' $'    a = k(x) + g(y) + t'` rather than partial matches like `edit $'a = f(x)' $'b = k(x)'`.

  4. Insert Command:
   - Specify the exact line number for insertion.
   - This command will not modify content before or after the specified line.

  5. Append Command:
   - Use `append` to add content to the end of a file without modifying any existing lines.
   - This is ideal after a `create_file` command.

  6. Search Command:
   - `search_repo` searches the current repository for specified functions or classes.
   - It provides definition (def) and reference (ref) relationships for the search term.
   - `search_term` is the function or class name to search for.

  7. Execute_server Command:
   - Use the `execute_server` command to run a server or process in the background. 
   - Usage: `execute_server 'Your_Command'`. Make sure to use quotes around the command.
   - `execute_server get_logs`: Retrieves the last 100 lines of the server / process logs.
   - `execute_server stop`: Stops the background Bash server process.

  (Open file: {open_file})
  (Current directory: {working_dir})
  bash-$
next_step_template: |-
  {observation}
  (Open file: {open_file})
  (Current directory: {working_dir})
  bash-$
next_step_no_output_template: |-
  Your command ran successfully and did not produce any output.
  (Open file: {open_file})
  (Current directory: {working_dir})
  bash-$
next_step_codegraph_template: |-
  Your command ran successfully and produced the following related functions/classes for {search_term}:
  For each item, `fname` denotes the source file, `line` denotes the line number, `kind` means whether it is definition or reference, and `info` contains the specific content.
  {codegraph_context}
  (Open file: {open_file})
  (Current directory: {working_dir})
  bash-$
demonstration_template: |
  Here is a demonstration of how to correctly accomplish this task.
  It is included to show you how to correctly use the interface.
  You do not need to follow exactly what is done in the demonstration.
  --- DEMONSTRATION ---
  {demonstration}
  --- END OF DEMONSTRATION ---
state_command:
  name: state
  code: |
    state() {
      local working_dir="$PWD";
      if [ -z "$CURRENT_FILE" ] || [ ! -f "$CURRENT_FILE" ]; then
          [ -n "$CURRENT_FILE" ] && [ ! -f "$CURRENT_FILE" ] && unset CURRENT_FILE;
          echo '{"open_file": "n/a", "working_dir": "'$working_dir'"}';
      else
          echo '{"open_file": "'$(realpath $CURRENT_FILE)'", "working_dir": "'$working_dir'"}';
      fi
    };
parse_function: ThoughtActionParser
env_variables:
  WINDOW: 100
  OVERLAP: 2
  CURRENT_LINE: 0
  CURRENT_FILE: ''
  SEARCH_RESULTS: ()
  SEARCH_FILES: ()
  SEARCH_INDEX: 0
command_files:
- config/commands/defaults.sh
- config/commands/search.sh
- config/commands/_split_string.py
- config/commands/_edit.py
- config/commands/_undo_edit.py
- config/commands/_agent_skills.py
- config/commands/_insert.py
- config/commands/_linter.py
- config/commands/_append.py
- config/commands/_execute_ipython.py
- config/commands/_python_cell_server.py
- config/commands/_execute_server.py
- config/commands/_bash_server.py
- config/commands/_code_graph.py

parse_command: ParseCommandDetailed
history_processor: Last5Observations
demonstrations:
- trajectories/demonstrations/marshmallow-code__marshmallow-1867-aider/marshmallow-code__marshmallow-1867.traj

agent_type: SWE-agent
codegraph_cache_dir: 'repograph/codegraph_cache/'
use_demonstrations: true
use_browse_web: false
swe_agent_checkpoint_path: null